### ISSUE TITLE
Show deployment as failed if no release?

### ISSUE THREAD

**Issue by jamietanna** [co-cddo/api-standards-linting#19]
```

Run JS-DevTools/npm-publish@v1
  with:
    package: spectral-ruleset-govuk-public/package.json
    access: public
    token: ***
    registry: https://registry.npmjs.org/
    tag: latest
    dry-run: false
    check-version: true

📦 @govuk-data-standards/spectral-ruleset-govuk-public v0.1.0 is already published to NPM
```
